[app]
title = My Phone Control
package.name = phonecontrol
package.domain = org.control
source.include_exts = py,png,jpg,kv,atlas
source.dir = .
version = 1.0
requirements = python3,requests
orientation = portrait
osx.python_version = 3
osx.kivy_version = 1.9.1
fullscreen = 0
android.permissions = INTERNET,READ_CONTACTS,READ_SMS,ACCESS_FINE_LOCATION,CAMERA,RECORD_AUDIO,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE
android.api = 33
android.minapi = 21
android.sdk = 33
android.ndk = 25b
android.archs = arm64-v8a
android.accept_sdk_license = True
